# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.155.2+26.1.2

# Mod Properties
mod_version=1.1.7
maven_group=tk.estecka.invarpaint.stockbook
archives_base_name=invarpaint-stockbook

# Dependencies
invarpaint_version=4.0.4+26.1.2
